# Generated by Django 5.2.7 on 2025-10-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default=None, upload_to='courses/%Y/%m'),
        ),
    ]
